-- 共享表：两个实体共同的订单结构（文档 6.1）
-- 共享表的破坏性变更必须走 expand-and-contract：先 expand（加新列/新表，双写）
-- → 两个实体都升级完毕 → 后 contract（删旧列）。contract 不可逆，需评审确认。
CREATE TABLE orders (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item           VARCHAR(255) NOT NULL,
    quantity       INTEGER      NOT NULL,
    price_amount   DECIMAL(19, 2),
    price_currency VARCHAR(3)
);
