-- Outbox 事件表（组件 12，文档 7.7.2）：与业务表同事务写入，relay 轮询发布
-- 生产替换为真实 MQ Sender；表本身是与业务表同事务的可靠事件落盘
-- relay 由 ShedLock 保护防多实例重复发送（组件 13）
CREATE TABLE outbox_event (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(64)  NOT NULL,
    aggregate_id   VARCHAR(64)  NOT NULL,
    event_type     VARCHAR(64)  NOT NULL,
    payload        VARCHAR(2000),
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    published_at   TIMESTAMP WITH TIME ZONE
);
