-- Alpha 实体专属表：风控规则（文档 6.1：实体专属表/字段进 per-entity 目录）
-- 本脚本随 entity-alpha 模块打包，实体 B 的镜像中不存在——分库后可独立升级 schema。
CREATE TABLE alpha_risk_rule (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_code VARCHAR(64)  NOT NULL,
    threshold DECIMAL(19, 2) NOT NULL
);
