-- Beta 实体专属表：审计扩展字段（文档 6.1：实体专属表/字段进 per-entity 目录）
-- 本脚本随 entity-beta 模块打包，实体 A 的镜像中不存在——分库后可独立升级 schema。
CREATE TABLE beta_audit_extra (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_code VARCHAR(64) NOT NULL,
    payload    VARCHAR(2000)
);
